podTemplate(
    containers: [
        containerTemplate(name: 'node', image: 'node:18-alpine', command: 'cat', ttyEnabled: true),
        containerTemplate(name: 'docker', image: 'docker:20.10-cli', command: 'cat', ttyEnabled: true,privileged: true),
        containerTemplate(name: 'sonar-scanner', image: 'sonarsource/sonar-scanner-cli:latest', command: 'sleep',args: '9999999', ttyEnabled: false),
        containerTemplate(name: 'trivy', image: 'aquasec/trivy:latest', command: 'cat', ttyEnabled: true)
    ],
    volumes: [ hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock') ]
) {
    node(POD_LABEL) {
        
        // ==================== EDIT THIS LINE ONLY ====================
        def DOCKER_REGISTRY = "meno0123" 
        // =============================================================

        def IMAGE_NAME    = "${DOCKER_REGISTRY}/ecommerce"
        def IMAGE_TAG     = "v${env.BUILD_NUMBER}"
        def SONAR_HOST    = "http://3.238.154.243:9000/"
        def SONAR_KEY     = "depi-test-project"
        
        // Ensure this points to your actual backend deployment yaml inside the repo:
        def MANIFEST_PATH = "k8s/back/back-deployment-svc.yaml" 

        try {
            stage('1. Checkout Code') { 
                checkout scm 
            }

            // ==========================================
            // ADD THIS TEST STAGE
            // ==========================================
            stage('Test WebSocket / Exec') {
                container('node') {
                    sh 'echo "If you see this, WebSockets work and the node container is alive!"'
                }
            }
            // ==========================================

            
            stage('2. SonarQube Analysis') {
                container('sonar-scanner') {
                    withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                        sh """
                        sonar-scanner \
                          -Dsonar.projectKey=${SONAR_KEY} \
                          -Dsonar.sources=./backend \
                          -Dsonar.host.url=${SONAR_HOST} \
                          -Dsonar.token=\$SONAR_TOKEN
                        """
                    }
                }
            }

            stage('3. Build Docker Image') {
                container('docker') {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ./backend"
                }
            }

            stage('4. Trivy Vulnerability Scan') {
                container('trivy') {
                    sh "trivy image --exit-code 0 --severity HIGH ${IMAGE_NAME}:${IMAGE_TAG}"
                    sh "trivy image --exit-code 0 --severity CRITICAL ${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }

            stage('5. Push to DockerHub') {
                container('docker') {
                    withCredentials([usernamePassword(credentialsId: 'docker-cred', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                        sh """
                        echo "\${PASS}" | docker login -u "\${USER}" --password-stdin
                        docker push ${IMAGE_NAME}:${IMAGE_TAG}
                        """
                    }
                }
            }

            stage('6. GitOps: Update K8s Manifest') {
               container('node') {
                    withCredentials([usernamePassword(credentialsId: 'github-creds',
                                                    passwordVariable: 'GPASS',
                                                    usernameVariable: 'GUSER')]) {
                        sh """
                        apk add --no-cache git

                        git config --global --add safe.directory \$WORKSPACE

                        git config --global user.email "jenkins@nhahub.local"
                        git config --global user.name "Jenkins CI Bot"

                        cd \$WORKSPACE

                        sed -i -E "s|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|" ${MANIFEST_PATH}

                        git add ${MANIFEST_PATH}
                        git commit -m "ci(backend): update image to ${IMAGE_TAG} [skip ci]" || echo "No manifest changes"

                        git push https://\${GUSER}:\${GPASS}@github.com/nhahub/NHA-4-147.git HEAD:main
                        """
                    }
                }
            }

        }
        finally{
            cleanWs()
        }
    }
}
