---
# Node exporter port
node_exporter_web_listen_address: "0.0.0.0:9100"

# Promtail  which logs to ship to Loki
promtail_config_scrape_configs:
  - job_name: "system"
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          host: "{{ inventory_hostname }}"
          __path__: /var/log/*.log

  - job_name: "journal"
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
        host: "{{ inventory_hostname }}"
    relabel_configs:
      - source_labels: [__journal__systemd_unit]
        target_label: unit


promtail_version: "3.5.8"
promtail_loki_server_url: "http://{{ monitoring_server_ip }}:3100/loki/api/v1/push"