apiVersion: v1
kind: Secret
metadata:
  name: back-secret 
  namespace: back-proj-ns
type: Opaque

stringData:
  # MONGO_URI : "mongodb://root:example@mongodb-clusterip-svc.mongodb-proj-ns.svc.cluster.local:27017/mern_ecommerce?authSource=admin&replicaSet=rs0"
  MONGO_URI: "mongodb://root:example@db-ss-0.mongo-svc-headless.mongodb-proj-ns.svc.cluster.local:27017,db-ss-1.mongo-svc-headless.mongodb-proj-ns.svc.cluster.local:27017/mern_ecommerce?authSource=admin&replicaSet=rs0"
  SECRET_KEY: "mine_secret_key"


  ORIGIN: "http://192.168.163.136:30019" ## we will change with the service DNS name first if not working like docker compose we will change the port of nodeport only


  EMAIL: "abdogomaa0155208@gmail.com"
  PASSWORD: "uihc kggw avqx hduf" ## app password 

  LOGIN_TOKEN_EXPIRATION: "30d"  # Days
  OTP_EXPIRATION_TIME: "120000"  # Milliseconds
  PASSWORD_RESET_TOKEN_EXPIRATION: "2m"  # Minutes
  COOKIE_EXPIRATION_DAYS: "30"    # Days
  PRODUCTION: "false"