
---
- name: Detect OS and set variables
  ansible.builtin.include_tasks: os_vars.yaml

- name: Install and configure PostgreSQL
  ansible.builtin.include_tasks: postgresql.yaml
  tags: postgresql

- name: Install and configure SonarQube
  ansible.builtin.include_tasks: sonarqube.yaml
  tags: sonarqube
