apiVersion: v1
kind: Namespace
metadata:
  name: mongodb-proj-ns


---
apiVersion: v1
kind: Namespace
metadata:
  name: back-proj-ns


---

apiVersion: v1
kind: Namespace
metadata:
  name: front-proj-ns