apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret 
  namespace: mongodb-proj-ns
type: Opaque

stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: example
  MONGO_INITDB_DATABASE: mern_ecommerce

  mongo-keyfile: |
    '/M6zR5I+mrn7FIieLWRX6t6ohOyzIUAZAGAhp/mfQQu9cWvg+FRwDG/mTrguH4hA
    A1dS4PIMyR9JBdS+voUElBPf0b/Y8adBr5xUpjDTJK29Kn0lTriIcwWdwZLlJHXW
    +Ji09rpv9NouJkBZl8MNVZR1AGuCzxPj9hpVAZw/3g5S4aF3mz07C0CKCnuMIrFQ
    rF+cQs/FbJ9ji168l2b2Z7QPGPujHdKxL1UhN8Qlf1LedatjM7o6y2cKzFp0Y0tE
    +NerxiUBUSwk5hgCSR0wi0vd3htkI/QDtjx2a4D+jrNuJ5zaB93ImcIxTW3jFeuO
    7x7nIvjMEgcTTx+yYDu2R2Jjf+njd4xNCfBeXl5QlEPpezgDLOjmd/6RD7UYclUr
    hDkvoz4UOgyYtcGyzUXAMsln2GowS98VNozrhERdJ2R6vSBBzu9IrEwBCMTd/E1x
    5mHRZygArRjBfo2imOYT4ZPcn3HE6kmmVE8PH17n7DZzVk+yp9kTlbG4vHJV2l6b
    yVmUK9jHRu1yILVRcKqpySguq3uhHDHiCt+g/qniL6HwS3Et3+oKcHAbfSrZ/ykI
    n6e8G4vQPMxKyQcwSxh9w6Rsx0o4nraQQ5LSC5ZHz4gY1bvGA8DqYSNH2tsAfW4o
    EvEyJ6dxuod/+XYW6Fv8aO6+tAtGN88AGcZQFf+cyhi4u8CrCEeE9tE7/jHpVXOV
    419Sixd8oaM+h2RwM6xvV0LBYnNE+9AAkNzV8H6NicyY+8pLCjA8piGyI2bCQLyl
    GZRPhZ8vuZb71gVkOlcmoumqxu7tHGDe+fZY63/8gZqDL4k+e4Kup7yHhi6W2jDq
    tBOHPkg056EDK4FbYDgkL1pPr4DYPj5/5TdLQ26i4fNYVhkY++lMLkTfuNxfv0fi
    5fqJLCr0S13rc5Pv3H6RDqA6H9qMOEkST3wB64uVhyny6PzcoGf3JHXKuQ/kEFuh
    BtTG9fQ43gl+8shzx2ValLLvZK7dIBiryLcP0AV4GObNrSbZ'
