apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-back-secret 
  namespace: {{ .Values.back_ns | default "back-proj-ns"}}
type: Opaque

stringData:
  # MONGO_URI : "mongodb://root:example@mongodb-clusterip-svc.mongodb-proj-ns.svc.cluster.local:27017/mern_ecommerce?authSource=admin&replicaSet=rs0"
  MONGO_URI: "mongodb://root:example@{{ .Release.Name }}-db-ss-0.{{ .Release.Name }}-mongo-svc-headless.{{ .Values.global.mongodb_ns | default "mongodb-proj-ns"}}.svc.cluster.local:27017,{{ .Release.Name }}-db-ss-1.{{ .Release.Name }}-mongo-svc-headless.{{ .Values.global.mongodb_ns | default "mongodb-proj-ns"}}.svc.cluster.local:27017/mern_ecommerce?authSource=admin&replicaSet=rs0"
  SECRET_KEY: "mine_secret_key"


  ORIGIN: "http://{{ .Values.global.nodeIP }}:{{ .Values.global.front_nodeport }}" ## we will change with the service DNS name first if not working like docker compose we will change the port of nodeport only


  EMAIL: "abdogomaa0155208@gmail.com"
  PASSWORD: "uihc kggw avqx hduf" ## app password 

  LOGIN_TOKEN_EXPIRATION: "30d"  # Days
  OTP_EXPIRATION_TIME: "120000"  # Milliseconds
  PASSWORD_RESET_TOKEN_EXPIRATION: "2m"  # Minutes
  COOKIE_EXPIRATION_DAYS: "30"    # Days
  PRODUCTION: "false"
  
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: example
  MONGO_INITDB_DATABASE: mern_ecommerce
