---
# tasks file for k8s-workers

- name: Check if already joined
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Tasks for K8s workers
  block:
    - name: Join workers to cluster
      ansible.builtin.command:
        cmd: "{{ hostvars[groups['k8s_control_plane'][0]].k8s_join_command }}"

    - name: Debug hostname values
      ansible.builtin.debug:
        msg:
          - "inventory_hostname = {{ inventory_hostname }}"
          - "ansible_hostname = {{ ansible_hostname | default('UNDEFINED') }}"

    - name: Wait for nodes to become Ready in cluster
      ansible.builtin.shell: |
        kubectl get nodes -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}'
      register: cluster_nodes_status
      until: "'True' in cluster_nodes_status.stdout"
      retries: 30
      delay: 15
      delegate_to: "{{ groups['k8s_control_plane'][0] }}"
      changed_when: false

  when:
    - not kubelet_conf.stat.exists | default(false)

  tags: k8s-workers
