plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running

keyed_groups:
  - key: tags.Role
    prefix: ""

groups:
  k8s_cluster: >
    tags.Role == 'k8s_control_plane'
    or tags.Role == 'k8s_workers'

hostnames:
  - ip-address