plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running


groups:
  k8s_control_plane: tags.Role == 'k8s_control_plane'
  k8s_workers: tags.Role == 'k8s_workers'
  sonar: tags.Role == 'sonar'
  k8s_cluster: >
    tags.Role == 'k8s_control_plane'
    or tags.Role == 'k8s_workers'

hostnames:
  - ip-address
