[k8s_control_plane]
k8s-master ansible_host=192.168.163.144

[k8s_workers]
k8s-worker-01 ansible_host=192.168.163.143

[sonar]
k8s-worker-01 ansible_host=192.168.163.143



# keep this part when we work with AWS -> to make group of groups 
[k8s_cluster:children]
k8s_control_plane
k8s_workers


