apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mongo-pv-1
  
spec:
  capacity:
    storage: 2Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /mnt/helm/data/mongo-1
    type: DirectoryOrCreate
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mongo-pv-2
spec:
  capacity:
    storage: 2Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /mnt/helm/data/mongo-2
    type: DirectoryOrCreate
