apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-mongo-rs-init
  namespace: {{ .Values.global.mongodb_ns | default "mongodb-proj-ns"}}

spec:
  template:
    spec:
      restartPolicy: OnFailure

      containers:
      - name: {{ .Release.Name }}-mongo-init
        image: mongo:7
      
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-db-secret 
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-db-secret 
                key: MONGO_INITDB_ROOT_PASSWORD

        command:
        - /bin/sh
        - -c
        - |
          sleep 60
          
          mongosh {{ .Release.Name }}-db-ss-0.{{ .Release.Name }}-mongo-svc-headless.{{ .Values.global.mongodb_ns | default "mongodb-proj-ns"}}.svc.cluster.local:27017 -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD"  --authenticationDatabase admin --eval '
          rs.initiate({
            _id:"rs0",
            members:[
              {_id:0,host:"{{ .Release.Name }}-db-ss-0.{{ .Release.Name }}-mongo-svc-headless.{{ .Values.global.mongodb_ns | default "mongodb-proj-ns"}}.svc.cluster.local:27017"},
              {_id:1,host:"{{ .Release.Name }}-db-ss-1.{{ .Release.Name }}-mongo-svc-headless.{{ .Values.global.mongodb_ns | default "mongodb-proj-ns"}}.svc.cluster.local:27017"}
            ]
          })
          '