apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed
  namespace: back-proj-ns
  labels:
    app: ecommerce
    tier: backend
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 180    # hard kill after 3 min regardless
  ttlSecondsAfterFinished: 120  # auto-delete 2 min after completion
  template:
    spec:
      restartPolicy: OnFailure

      initContainers:
      - name: wait-for-mongodb
        image: mongo:7
        command:
          - /bin/sh
          - -c
          - |
            MONGO_HOST="db-ss-0.mongo-svc-headless.mongodb-proj-ns.svc.cluster.local:27017"
            echo "Waiting for MongoDB primary..."
            until mongosh "$MONGO_HOST" \
              -u root \
              -p example \
              --authenticationDatabase admin \
              --quiet \
              --eval 'db.runCommand({isMaster:1}).ismaster' 2>/dev/null | grep -q "true"; do
              echo "No primary yet, retrying in 5s..."
              sleep 5
            done
            echo "MongoDB primary is ready."

      containers:
      - name: db-seed
        image: abdulrahman011/devops_comprehensive_project_depi_back_svc
        command:
          - /bin/sh
          - -c
          - |
            echo "Starting database seeding..."
            cd /app && timeout 90 npm run seed || true
            echo "Seeding complete."
            exit 0
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: back-secret
                key: MONGO_URI
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: back-secret
                key: SECRET_KEY
          - name: ORIGIN
            valueFrom:
              secretKeyRef:
                name: back-secret
                key: ORIGIN
          - name: EMAIL
            valueFrom:
              secretKeyRef:
                name: back-secret
                key: EMAIL
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: back-secret
                key: PASSWORD
          - name: LOGIN_TOKEN_EXPIRATION
            valueFrom:
              secretKeyRef:
                name: back-secret
                key: LOGIN_TOKEN_EXPIRATION
          - name: OTP_EXPIRATION_TIME
            valueFrom:
              secretKeyRef:
                name: back-secret
                key: OTP_EXPIRATION_TIME
          - name: PASSWORD_RESET_TOKEN_EXPIRATION
            valueFrom:
              secretKeyRef:
                name: back-secret
                key: PASSWORD_RESET_TOKEN_EXPIRATION
          - name: COOKIE_EXPIRATION_DAYS
            valueFrom:
              secretKeyRef:
                name: back-secret
                key: COOKIE_EXPIRATION_DAYS
          - name: PRODUCTION
            valueFrom:
              secretKeyRef:
                name: back-secret
                key: PRODUCTION